version: '3'

services:
  app:
    image: hackathonapifin
    ports:
      - 42096:8080
    volumes:
      - ./files:/usr/src/app/files
      - ./configs:/ap10p
    networks:
      - hackathon-network
  pdfToTxt:
    image: pdf-to-text
    networks:
      - hackathon-network
    volumes:
      - ./configs:/app/conf
  txtToPdf:
    image: text-to-json
    networks:
      - hackathon-network
    volumes:
      - ./configs:/app/conf

networks:
  hackathon-network:
    driver: bridge

