version: '3'

services:
  app:
    image: hackathonapifin
    ports:
      - 42096:8080
    volumes:
      - ./files:/usr/src/app/files
      - ./configs/configMain.ini:/app/configMain.ini
    networks:
      - hackathon-network
  pdfToTxt:
    image: pdf_to_text
    networks:
      - hackathon-network
    volumes:
      - ./configs:/app/conf
  txtToPdf:
    image: text_to_json
    networks:
      - hackathon-network
    volumes:
      - ./configs:/app/conf

networks:
  hackathon-network:
    driver: bridge

